#!/bin/bash

echo "installing homebrew"
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
brew doctor
brew update

echo "after homebrew is installed update the path"
echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.bashrc
source ~/.bashrc

echo "fix required before we can install rvm / ruby"
brew install libksba

echo "install rvm / fix gcc / install the latest ruby"
curl -L https://get.rvm.io | bash -s stable --rails --ignore-dotfiles
source ~/.rvm/scripts/rvm
echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc
source ~/.bashrc
sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.2

echo "install the fundamentals"
brew install tig
brew install node
brew install phantomjs
brew install ack
brew install tmux
brew install postgresql
brew install mysql
brew install mongo

echo "add bundler and a few other rails gems"
rvm use 2.0
gem install bundler rails pg foreman thin --no-rdoc --no-ri

echo "setup pip and virtualenv"
sudo easy_install pip
sudo pip install virtualenvwrapper

echo "add jedi globally for better python support in vim"
sudo pip install jedi

echo "finish the postgres setup"
initdb /usr/local/var/postgres -E utf8

echo "add color support for git cli"
git config --global color.status auto
git config --global color.diff auto

echo "install the latest vim"
brew install mercurial
brew install vim

echo "install zsh"
brew install zsh

# todo => add true exuberant ctags support
# curl -O https://dl.dropboxusercontent.com/u/716525/content/downloads/ctags-5.8.tar.gz
# tar xvzf ctags-5.8.tar.gz
# cd ctags-5.8 && ./configure && make && make install
# export PATH="/usr/local/bin:$PATH"

# todo => install virtualbox
# https://www.virtualbox.org/wiki/Downloads
