#!/bin/bash

echo "installing homebrew"
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
brew doctor
brew update

echo "after homebrew is installed update the path"
echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.bashrc
source ~/.bashrc

echo "installing git"
brew install git

echo "fix required before we can install rvm / ruby"
brew install libksba

echo "install rvm / fix gcc / install the latest ruby"
curl -L https://get.rvm.io | bash -s stable --rails --ignore-dotfiles
source ~/.rvm/scripts/rvm
echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc
source ~/.bashrc
sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.2

echo "install the fundamentals"
brew install tig
brew install node
brew install phantomjs
brew install ack
brew install tmux
brew install postgresql
brew install mysql
brew install mongo

echo "add bundler and a few other rails gems"
rvm use 2.0
gem install bundler rails pg foreman thin --no-rdoc --no-ri

echo "setup pip and virtualenv"
sudo easy_install pip
sudo pip install virtualenvwrapper

echo "add jedi globally for better python support in vim"
sudo pip install jedi

echo "finish the postgres setup"
initdb /usr/local/var/postgres -E utf8

echo "install the latest vim"
brew install mercurial
brew install vim

echo "install zsh"
brew install zsh

echo "pull down zsh/tmux/vim dotfiles"
git clone https://github.com/JarrodCTaylor/imt_dotfiles.git ~/

echo "install exuberant-ctags"
brew install ctags 
sudo mv /usr/bin/ctags /usr/bin/ctags_orig

echo "add GNU gettext and gettext-tools for django compile messages"
brew install gettext
brew link gettext --force

echo "change the default shell to zsh"
chsh -s /bin/zsh

echo "silence rvm when its not the first item on the path"
touch ~/.rvmrc
echo rvm_silence_path_mismatch_check_flag=1 >> ~/.rvmrc

echo "install nvm for better node version management"
curl https://raw.github.com/creationix/nvm/master/install.sh | sh
